apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secret-scanner
spec:
  entrypoint: entry
  parallelism: 1
  templates:
    - name: entry
      dag:
        tasks:
          - name: generate-artifact-all-repo
            template: getallrepo

          - name: scan-cloned-repo
            template: scan-with-trufflehog
            dependencies: [generate-artifact-all-repo]
            arguments:
              parameters:
                - name: repo
                  value: "{{item}}"
            withParam: "{{tasks.generate-artifact-all-repo.outputs.parameters.repos}}"

    - name: getallrepo
      script:
        image: dwdraju/alpine-curl-jq
        command: [sh]
        source: |
          GHUSER=microsoft; curl "https://api.github.com/users/$GHUSER/repos?per_page=100" | grep  'clone_url' |cut -f 4 -d '"' | jq -R -s -c 'split("\n")' >/tmp/allrepos.json
      outputs:
        parameters:
          - name: repos
            valueFrom:
              path: /tmp/allrepos.json

    - name: scan-with-trufflehog
      inputs:
        parameters:
          - name: repo
      script:
        image: nahidupa/trufflehog:latest
        command: [sh]
        source: |
            REPONAME=$(echo {{inputs.parameters.repo}} | cut -f 5 -d "/" | cut -f 1 -d "." ) ; cd /tmp;git clone {{inputs.parameters.repo}} $REPONAME;trufflehog  $REPONAME > /tmp/scan_output.txt
      outputs:
        artifacts:
          - name: scanoutput_{{pod.name}}
            path: /tmp/scan_output.txt
