apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer #ClusterIP LoadBalancer
  selector:
    controller: eventsource-controller
    eventsource-name: webhook
    owner-name: webhook
  ports:
    - port: 12000
      targetPort: 12000
