apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    bitbucket:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /bitbucket
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST