apiVersion: v1
kind: ConfigMap
metadata:
  # if you want to use this config map by default - name it "artifact-repositories"
  name: artifact-repositories
  annotations:
    # if you want to use a specific key, put that's key into this annotation
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |
    s3:
      bucket: argo-work-flow-artifact-eks-sonarqube
      keyFormat: prefix/in/bucket
      endpoint: s3.amazonaws.com
      accessKeySecret:
        name: argo-work-flow-s3-cred
        key: accessKey
      secretKeySecret:
        name: argo-work-flow-s3-cred
        key: secretKey
      useSDKCreds: true
